version: 2.0

jobs:
  build_and_test:
    docker:
      - image: passfort/rust-musl-builder:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-cargo-deps-{{ checksum "Cargo.lock" }}
            - v1-cargo-deps
      - run: cargo build --release --target=x86_64-unknown-linux-musl
      - run: cargo test --release --target=x86_64-unknown-linux-musl
      - save_cache:
          key: v1-cargo-deps-{{ checksum "Cargo.lock" }}-{{ checksum "config.yml" }}
          paths:
            - /home/root/.cargo
            - target
      - persist_to_workspace:
          root: .
          paths:
            - target/x86_64-unknown-linux-musl/release/checkout
            - Dockerfile
  deploy:
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Authenticate to GCP
          command: |
              echo $GCLOUD_SERVICE_KEY | base64 --decode --ignore-garbage > ${HOME}/gcloud-service-key.json
              gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
              gcloud config set compute/zone europe-west1-b
              gcloud config set project core-gearbox-112418
      - run: |
          gcloud container builds submit --tag $PROJECT_URI/checkout .
workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test
