version: 2.0

jobs:
  build:
    docker:
      - image: passfort/rust-musl-builder:latest
    steps:
      - checkout
      - run: cargo build --release --target=x86_64-unknown-linux-musl
      - run: cargo test --release --target=x86_64-unknown-linux-musl

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
