apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: checkout
spec:
  replicas: 3
  selector:
    matchLabels:
      passfort: checkout
  progressDeadlineSeconds: 120
  template:
    metadata:
      name: checkout
      labels:
        passfort: checkout
    spec:
      volumes:
        - name: cloudsql
          emptyDir:

      containers:
        - name: checkout
          image: $PROJECT_URI/checkout:$CIRCLE_SHA1
        - name: cloudsql-proxy
          image: b.gcr.io/cloudsql-docker/gce-proxy:1.09
          resources:
            requests:
              cpu: "50m"
          command: ["/cloud_sql_proxy", "--dir=/cloudsql",
                  "-instances=core-gearbox-112418:europe-west1:$DATABASE_NAME=tcp:5432"]
          volumeMounts:
            - name: cloudsql
              mountPath: /cloudsql